version: "3"
services:
  db:
    container_name: "tipxmr-db"
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - tipxmr-db:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=tipxmr
      - POSTGRES_USER=tipxmr
      - POSTGRES_PASSWORD=tipxmr
    ports:
      - 5432:5432

  monerod:
    container_name: "tipxmr-monerod"
    platform: linux/arm64/v8
    build:
      context: ./monero
      dockerfile: arm.Dockerfile
    command: --non-interactive --config-file /home/monero/.bitmonero/stagenet.conf
    ports:
      - "38080:38080"
      - "38081:38081"
    volumes:
      - ./monero/bitmonero:/home/monero/.bitmonero
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

volumes:
  tipxmr-db:
