version: "3"
services:
  db:
    container_name: "tipxmr-db"
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=tipxmr
      - POSTGRES_USER=tipxmr
      - POSTGRES_PASSWORD=tipxmr
    ports:
      - 5432:5432

  pgadmin:
    container_name: "tipxmr-pgadmin"
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tipxmr.live
      PGADMIN_DEFAULT_PASSWORD: tipxmr
    restart: unless-stopped
    logging:
      driver: none

  monerod:
    container_name: "tipxmr-monerod"
    platform: linux/amd64
    build:
      context: ./monero
    command: --non-interactive --config-file /home/monero/.bitmonero/stagenet.conf
    ports:
      - "38080:38080"
      - "38081:38081"
    volumes:
      - ./monero/bitmonero:/home/monero/.bitmonero
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
