-- AlterTable
ALTER TABLE "Donation_settings" ALTER COLUMN "goal" SET DEFAULT 0,
ALTER COLUMN "charLimit" SET DEFAULT 140,
ALTER COLUMN "charPrice" SET DEFAULT 0,
ALTER COLUMN "gifsMinAmount" SET DEFAULT 0,
ALTER COLUMN "goalProgress" SET DEFAULT 0,
ALTER COLUMN "goalReached" SET DEFAULT false,
ALTER COLUMN "minAmount" SET DEFAULT 0,
ALTER COLUMN "secondPrice" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "Streamer" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "isOnline" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "status" "Statuses",
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
