-- AlterTable
ALTER TABLE "Donation" ALTER COLUMN "amount" SET DEFAULT 0,
ALTER COLUMN "message" SET DEFAULT E'',
ALTER COLUMN "confirmations" SET DEFAULT 0,
ALTER COLUMN "donor" SET DEFAULT E'',
ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "displayTimeSeconds" SET DEFAULT 0,
ALTER COLUMN "giphyUrl" SET DEFAULT E'';
